### ISSUE TITLE
Add missing Cropped field for the Image struct

### ISSUE THREAD

**Issue by curiosport** [Doarakko/go-yugioh#18]
https://github.com/Doarakko/go-yugioh/blob/66cd1b526f3506beb02a1d8edd23f0db67f6d34f/yugioh/cards.go#L85
```
// Image card image.
type Image struct {
	ID       int32  `json:"id"`
	URL      string `json:"image_url"`
	SmallURL string `json:"image_url_small"`
	Cropped  string `json:"image_url_cropped"
}
```
According to the API json file there is a third field that is not included in this repository:
https://db.ygoprodeck.com/api/v7/cardinfo.php

**Comment by Doarakko** [comment]
@curiosport 
I added other missing fields and release new version.
Thanks for the issue!
https://github.com/Doarakko/go-yugioh/releases/tag/v1.3.0
